name: DeployToItch

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"
env:
  ITCH_USERNAME: texandoomguy2
  ITCH_GAME_ID: 3514652
jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - webgl
    steps:
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_CREDENTIALS}}
          gameData: ./build/Web
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ github.event.inputs.tag_name || github.ref_name }}
          buildChannel: webgl
          buildNumber: ${{ needs.version.outputs.version_hash }}
