on: # Made from an example on the firebelley/godot-export repo and chatgpt. I'm not bothered to lean yml.
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"
permissions:
  contents: write
jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      - name: export game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./project # build the standard project
          relative_export_path: ./build # move export output to this directory relative to git root
          archive_output: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      - name: Print something
        run: echo github.event.inputs.tag_name
      - name: create release
        uses: ncipollo/release-action@v1.16.0
        with:
          generateReleaseNotes: true
          tag: ${{ github.event.inputs.tag_name || github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/* # Added "/*" at the end is glob pattern match for this action
